20-rails-validations/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :movies #, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  resources :characters, only: [:index, :new, :create, :edit, :update]
  # To display all the movies
  # get '/movies', to: 'movies#index'

  # # # To give new movie form
  # get '/movies/new', to: 'movies#new'

  # # # To display single movie's info
  # get '/movies/:id', to: 'movies#show'

  # # #create new movie
  # post '/movies', to: 'movies#create'

  # # # form to edit an existing movie
  # get '/movies/:id/edit', to: 'movies#edit', as: 'movie'

  # # # updating an existing movie
  # patch '/movies/:id', to: 'movies#update'

 
end

20-rails-validations/app/models/actor.rb
class Actor < ApplicationRecord
    has_many :characters
    has_many :movies, through: :characters
end

20-rails-validations/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

20-rails-validations/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :characters
    has_many :actors, through: :characters

    validates :title, presence: true, format: { with: /\A[0-9a-zA-Z]+\z/ }
    # Validates year for a movie => less than 2021 and greater than 1900
    validates :year, numericality: {only_integer: true, greater_than: 1900, less_than: 2021}
end

20-rails-validations/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
  end

  def new
    @character = Character.new
    @movies = Movie.all
    @actors = Actor.all
  end

  def create
    character = Character.create(character_params)
    # redirect_to character_path(character)
    redirect_to characters_path
  end

  def edit
    @character = Character.find(params[:id])
    @movies = Movie.all
    @actors = Actor.all
  end

  def update
    # byebug
    @character = Character.find(params[:id])
    @character.update(character_params)

    redirect_to characters_path
  end

  private
  def character_params
    params.require(:character).permit(:name, :movie_id, :actor_id)
  end
end

20-rails-validations/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    before_action :current_movie, only: [:show, :edit, :update, :destroy]

    def index
        @movies = Movie.all
    end

    def show
    end

    def new
        @movie = Movie.new
        @actors = Actor.all
    end

    def create
        # byebug
        movie = Movie.new(movies_params)
        # byebug
        if movie.valid?
            movie.save
            # redirect_to movie_path(movie)
            redirect_to movie
        else
            # byebug
            flash[:errors] = movie.errors.full_messages
            redirect_to new_movie_path
        end
    end

    def edit
        @actors = Actor.all
    end

    def update
        @movie.update(movies_params)
        redirect_to "/movies/#{@movie.id}"
    end

    def destroy
        @movie.destroy
        redirect_to movies_path
    end

    def current_movie
        @movie = Movie.find(params[:id])
    end

    private

    def movies_params
        params.require(:movie).permit(:title, :year, actor_ids: [])
    end

end

20-rails-validations/app/helpers/characters_helper.rb
module CharactersHelper
end

20-rails-validations/app/helpers/movies_helper.rb
module MoviesHelper
end

20-rails-validations/app/views/characters/_form.html.erb
<%= form_with(model: @character) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :movie %>
<%= f.collection_select(:movie_id, @movies, :id, :title)%>
<%= f.label :actor %>
<%= f.collection_select :actor_id, @actors, :id, :name%>

<%= f.submit %>
<% end %>

20-rails-validations/app/views/characters/index.html.erb
<h1>Characters:</h1>
<% @characters.each do |character| %>
<li>
    <%= character.name%>
</li>
<% end %>

20-rails-validations/app/views/characters/new.html.erb
<%= render "form"%>

20-rails-validations/app/views/characters/show.html.erb
<h1>Characters#show</h1>
<p>Find me in app/views/characters/show.html.erb</p>

20-rails-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetflixApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

20-rails-validations/app/views/movies/_form.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <li style="color: red">
        <%= e %>
        </li>
    <% end %>
<% end %>


<%= form_for @movie do |f|  %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :year %>
<%= f.text_field :year %>

<%= f.label :actors %>
<%= f.collection_check_boxes :actor_ids, @actors, :id, :name%>

<%= f.submit %>

<% end %>

20-rails-validations/app/views/movies/edit.html.erb
<%= render 'form' %>

20-rails-validations/app/views/movies/index.html.erb
<!-- <%= @temp %> -->

<label>Movies: </label>
<% @movies.each do |movie| %>
    <li>
    <!-- <%= movie.title %> -->
    <!-- <%= link_to movie.title, "/movies/#{movie.id}"%> -->
    <%= link_to movie.title, movie_path(movie)%>

    </li>
<% end %>

20-rails-validations/app/views/movies/new.html.erb
<%= render 'form' %>

20-rails-validations/app/views/movies/show.html.erb
<label> Movie Title: </label>
<%= @movie.title %>
<br/>
<label> Movie release year: </label>
<%= @movie.year %>

<% @movie.characters.each do |character| %>
<li>
character: <%= character.name%>
Actor: <%= character.actor.name%>
<%= link_to "Edit Character", edit_character_path(character)%>
</li>
<% end %>

<% @movie.actors.each do |actor| %>
<li>
Actor: <%= actor.name%>
</li>
<% end %>

<%= form_with model: @movie, method: :delete do |f|  %>
<%= f.submit "Delete Movie" %>
<% end %>

<!-- <%= form_with url:"/movies/#{@movie.id}" , method: :delete do |f|  %>
<%= f.submit "Delete Movie" %>
<% end %> -->